---
title: "Spatial cueing with and without flicker"
author: "Pierce Edmiston"
date: "April 28, 2015"
output: html_document
---

```{r, get-spatial-cueing, message = FALSE}
source("R/loaders.R")
cueing <- get_spatial_cueing(interval = 0.750, flicker = c("on", "off"))
cueing %>% group_by(interval, flicker, subj_id) %>%
  summarize(num_trials = n(),
            mean_acc = mean(is_correct))
```

# Cueing effect in accuracies
```{r, fit-glmer-mod, message = FALSE}
library(lme4)
library(broom)
source("R/recoders.R")

cueing <- set_treatment_contrasts(cueing)
cueing$flicker_c <- recode_flicker_as_centered_num(cueing)
cueing$flicker_lab <- label_flicker(cueing)

accuracy_mod <- glmer(data = cueing, family = "binomial",
  formula = is_correct ~ (frame_v_nocue + sound_v_nocue) * flicker_c + 
              (frame_v_nocue + sound_v_nocue || subj_id))
  ## the double pipe fits random intercepts and slopes without
  ## random effect correlations
tidy(accuracy_mod, effects = "fixed")
```

```{r, plot-accuracies, message = FALSE, fig.width = 10}
source("R/plots.R")
source("R/models.R")

# summarize the raw data by subject
cueing_by_subj <- cueing %>% group_by(flicker_lab, subj_id, cue_type) %>%
  summarize(accuracy = mean(is_correct))

# get the model estimates
x_preds <- expand.grid(cue_type = c("nocue", "frame", "sound"), flicker = c("on", "off")) %>%
  set_treatment_contrasts() %>%
  mutate(
    cue_type_int = recode_cue_type_as_int(.),
    flicker_c = recode_flicker_as_centered_num(.),
    flicker_lab = label_flicker(.)
  )
acc_mod_preds <- get_glmer_predictions(accuracy_mod, x_preds)

# base plot subj accuracies
acc_by_subj_plot <- plot_acc_by_subj(cueing_by_subj) +
  facet_wrap("flicker_lab", nrow = 1)

# add on model predictions
acc_mod_plot <- acc_by_subj_plot +
  geom_ribbon(aes(ymin = accuracy - se, ymax = accuracy + se),
    data = acc_mod_preds, fill = "gray", alpha = 0.8) +
  geom_line(aes(group = 1), data = acc_mod_preds)
acc_mod_plot
```

```{r}
glmer(is_correct ~ frame_v_nocue + sound_v_nocue + 
        (frame_v_nocue + sound_v_nocue||subj_id), 
      data = filter(cueing, flicker == "off"), family = "binomial") %>%
  tidy(effects = "fixed")
```

```{r, summarize-rts-for-plot, fig.width = 10}
source("R/recoders.R")
cueing$trial_type <- determine_trial_type(cueing)
hit_trials <- filter(cueing, trial_type == 'hit')

rts_by_subj <- hit_trials %>% group_by(flicker, subj_id, cue_type) %>%
  summarize(rt = mean(rt))

rts_by_subj$cue_type_int <- recode_cue_type_as_int(rts_by_subj)
rts_by_subj$cue_type_jit <- jitter_cue_type_int_by_subj(rts_by_subj)
rts_by_subj$flicker_lab <- label_flicker(rts_by_subj)

plot_rts_by_subj <- ggplot(rts_by_subj,
    aes(x = cue_type_int, y = rt)) +
  geom_point(aes(x = cue_type_jit, color = subj_id), shape = by_subj_point_shape) +
  geom_line(aes(x = cue_type_jit, color = subj_id), shape = by_subj_line_size) +
  facet_wrap("flicker_lab", nrow = 1) +
  scale_cue_type_int +
  scale_y_continuous("Response Time (ms)") +
  theme(legend.position = "none")
plot_rts_by_subj
```

Note the outliers.
```{r}
rts_by_subj %>% filter(flicker == "off", rt[cue_type == "frame"] > 450)
```

```{r, fit-lmer-model}
rt_mod <- lmer(rt ~ (frame_v_nocue + sound_v_nocue) * flicker_c +
                     (frame_v_nocue + sound_v_nocue || subj_id),
                   data = hit_trials)
summary(rt_mod)
```

```{r}
rt_mod_flicker_off <- lmer(rt ~ frame_v_nocue + sound_v_nocue + 
                             (frame_v_nocue + sound_v_nocue || subj_id),
                           data = filter(hit_trials, 
                                         flicker == "off", 
                                         !(subj_id %in% c("SPC408", "SPC413"))))
summary(rt_mod_flicker_off)
```
